require: rubocop-rspec
AllCops:
  Include:
    - 'app/**'
    - 'spec/**'
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 200

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 35

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false
