require: rubocop-rspec
AllCops:
  Include:
    - 'app/**'
    - 'spec/**'
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 200

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
    - '**/*_helper.rb'
    - 'lib/tasks/**/*'
    - 'Guardfile'

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Vagrantfile'
    - 'Guardfile'
