scss_files: 'app/assets/stylesheets/**/*.scss'
severity: error

linters:
  IdSelector:
    enabled: false
  ColorVariable:
    enabled: false
  NestingDepth:
    enabled: false
  SelectorDepth:
    enabled: false
