scss_files: 'app/assets/stylesheets/**/*.scss'

linters:
  IdSelector:
    enabled: false
  ColorVariable:
    enabled: false
  NestingDepth:
    enabled: false
  SingleLinePerSelector:
    enabled: false
  SelectorDepth:
    enabled: false
