sudo: false
cache: bundler
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
rvm:
  - 2.3.1
addons:
  postgresql: '9.4'
services:
  - postgresql
script:
  - bundle exec rubocop && bundle exec scss-lint && bundle exec brakeman -z && bundle exec bundle-audit && bundle exec rake db:migrate RAILS_ENV=test --trace && bundle exec rspec spec
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    on_start: always
    secure: vdBGEaiVigzjqIBsdxyrSohCn64LASApYF6i4EyEXm/nfHweCbwv13dz6mAidLt2U3X7p/P3xOFeWW8eUzj1rLAdnaJA14/GVZycuLrPDWOBsc+M4RpLg9cKhNGnxcFt4srU7QQdeyQbY8ssD0iqzFiNeIWZdp+u6R2A+QX+WgCm8uhWdFFxpTS5lKmXBH9L7VLQAw0wUuIW4H3s/awJY+HSAPtxqso0qFvGhfWxiYFHN09sfh49sTrBmmQeodcoeYH0w2eLhMEyJH8pZ4hREFuVwhbJlnTQRxhQUqm6WEUN9YrpEY2L8RdcnrG+0AG0UE9P7GBmlGr/k+1zEBtBms2S9lOKuW7ccquv0eLAe9gurgYpBjk562aR2p6nH7RX8MUu0nu0COGE24b4OQLr7RemVu7rRA3goflgomO9jZPgWmHss9GiVNHvRHdIvlV+OyQdDpyj9ulqhzghDiMcqOkXcC0viLM2rwgVTB65fZ3HsTZlhIduCCjONzxIIno9FbG6M9s0qLmvvL/7dgbP41y7qJZGM/SJ2rQFh9B7jWAmtDMgPpz3IlOuMuNQaJnW19VSfpklJQ+WOmjm7V8IXHUrCAJtPwmOlFmq1fKU/Q+2XVs1psX6Wl0sbGeHpla/Qfr0KGuA0lfFdBkJw4Xtgvnw43pnw7ZyrbkbhA9bzyA=
