before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
rvm:
  - 2.2.3
addons:
  postgresql: "9.4"
services:
  - postgresql
script: 
  - bundle exec rake db:migrate RAILS_ENV=test --trace
  - bundle exec rspec spec
