require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SpotsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Spot. As you add validations to Spot, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    attributes_for(:spot)
  }

  let(:invalid_attributes) {
    {
      "title" => "",
      "description" => ""
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SpotsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all spots as @spots" do
      spot = Spot.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:spots)).to eq([spot])
    end
  end

  describe "GET #show" do
    it "assigns the requested spot as @spot" do
      spot = Spot.create! valid_attributes
      get :show, {:id => spot.to_param}, valid_session
      expect(assigns(:spot)).to eq(spot)
    end
  end

  describe "GET #new" do
    it "assigns a new spot as @spot" do
      user = create(:user)
      sign_in user
      get :new, {}, valid_session
      expect(assigns(:spot)).to be_a_new(Spot)
    end
  end

  describe "GET #edit" do
    it "assigns the requested spot as @spot" do
      spot = Spot.create! valid_attributes
      get :edit, {:id => spot.to_param}, valid_session
      expect(assigns(:spot)).to eq(spot)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Spot" do
        user = create(:user)
        sign_in user
        expect {
          post :create, {:spot => valid_attributes}, valid_session
        }.to change(Spot, :count).by(1)
      end

      it "assigns a newly created spot as @spot" do
        user = create(:user)
        sign_in user
        post :create, {:spot => valid_attributes}, valid_session
        expect(assigns(:spot)).to be_a(Spot)
        expect(assigns(:spot)).to be_persisted
      end

      it "redirects to the map with the id in the param" do
        user = create(:user)
        sign_in user
        post :create, {:spot => valid_attributes}, valid_session
        expect(response).to redirect_to(spots_path(id: Spot.last.id))
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved spot as @spot" do
        user = create(:user)
        sign_in user
        post :create, {:spot => invalid_attributes}, valid_session
        expect(assigns(:spot)).to be_a_new(Spot)
      end

      it "goes to the map page" do
        user = create(:user)
        sign_in user
        post :create, {:spot => invalid_attributes}, valid_session
        expect(response).to redirect_to(spots_path)
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested spot" do
        user = create(:user)
        sign_in user
        user.spots.create! valid_attributes
        put :update, {:id => user.spots.last.to_param, :spot => {title: "test title"}}, valid_session
        user.spots.last.reload
        expect(user.spots.last.title).to eq("test title")
      end

      it "assigns the requested spot as @spot" do
        spot = Spot.create! valid_attributes
        put :update, {:id => spot.to_param, :spot => valid_attributes}, valid_session
        expect(assigns(:spot)).to eq(spot)
      end

      it "redirects to the spot" do
        user = create(:user)
        sign_in user
        user.spots.create! valid_attributes
        put :update, {:id => user.spots.last.to_param, :spot => valid_attributes}, valid_session
        expect(response).to redirect_to(user.spots.last)
      end
    end

    context "with invalid params" do
      it "assigns the spot as @spot" do
        spot = Spot.create! valid_attributes
        put :update, {:id => spot.to_param, :spot => invalid_attributes}, valid_session
        expect(assigns(:spot)).to eq(spot)
      end

      it "re-renders the 'edit' template" do
        user = create(:user)
        sign_in user
        spot = Spot.create! valid_attributes
        put :update, {:id => spot.to_param, :spot => invalid_attributes}, valid_session
        expect(response).to render_template()
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested spot" do
      user = create(:user)
      sign_in user
      spot = Spot.create! valid_attributes
      expect {
        delete :destroy, {:id => spot.to_param}, valid_session
      }.to change(Spot, :count).by(-1)
    end

    it "redirects to the user's profile" do
      user = create(:user)
      sign_in user
      spot = Spot.create! valid_attributes
      delete :destroy, {:id => spot.to_param}, valid_session
      expect(response).to redirect_to(show_user_url(user.username))
    end
  end

end
